name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every day
    - cron:  '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: HiSunzhenliang/HiSunzhenliang@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
